i2v: true
independent_first_frame: true

denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
num_frame_per_block: 4
model_kwargs:
  model_name: Wan2.2-TI2V-5B
  local_attn_size: 12
  timestep_shift: 5.0
  sink_size: 4
  MDS_with_relativeRope: true

whether_set_per_block_sink_size: true
sink_size_per_block:
- 7  # block 0
- 5  # block 1
- 7  # block 2
- 7  # block 3
- 8  # block 4
- 9  # block 5
- 7  # block 6
- 9  # block 7
- 8  # block 8
- 9  # block 9
- 9  # block 10
- 3  # block 11
- 8  # block 12
- 3  # block 13
- 3  # block 14
- 3  # block 15
- 3  # block 16
- 3  # block 17
- 2  # block 18
- 3  # block 19
- 4  # block 20
- 3  # block 21
- 3  # block 22
- 3  # block 23
- 3  # block 24
- 3  # block 25
- 3  # block 26
- 4  # block 27
- 4  # block 28
- 4  # block 29

learnable_mds: true

# inference
data_path: ''
output_folder: ''
inference_iter: -1
num_output_frames: 161
use_ema: false
seed: 0
num_samples: 1
save_with_index: true
global_sink: true
context_noise: 0
load_raw_video: true

generator_ckpt: ''
lora_ckpt: ''

adapter:
  type: "lora"
  rank: 256                    # LoRA rank (typical values: 8, 16, 32, 64)
  alpha: 256                   # LoRA alpha (typically same as rank, but can be different)
  dropout: 0.0                # LoRA dropout rate
  dtype: "bfloat16"          # Data type for LoRA parameters: "bfloat16", "float16", "float32"
  verbose: false              # Whether to print all target module names
