i2v: true
independent_first_frame: true

generator_ckpt: /m2v_intern_v3/raozejing/logs/longlive_dmd_init_chunkwise_only_3th_stage_with_HOIGen_dataset_origin_prompts/checkpoint_model_000321/model.pt
generator_fsdp_wrap_strategy: size
real_score_fsdp_wrap_strategy: size
fake_score_fsdp_wrap_strategy: size
# real_name: Wan2.2-TI2V-5B
real_name: Wan2.2-TI2V-5B
fake_name: Wan2.2-TI2V-5B
text_encoder_fsdp_wrap_strategy: size
# text_encoder_cpu_offload: true
denoising_step_list:
- 1000
- 750
- 500
- 250
warp_denoising_step: true # need to remove - 0 in denoising_step_list if warp_denoising_step is true
ts_schedule: false
num_train_timestep: 1000
timestep_shift: 5.0
guidance_scale: 5.0
denoising_loss_type: flow
mixed_precision: true
seed: 0
wandb_key: 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
wandb_entity: zjrao-ucas
wandb_project: Causal-Forcing-ind-new-TF
sharding_strategy: hybrid_full
lr: 1.0e-05
lr_critic: 2.0e-06
beta1: 0.0
beta2: 0.999
beta1_critic: 0.0
beta2_critic: 0.999
data_path: /m2v_intern/raozejing/StreamingCode/dataset/live_5s_final_mix_HOIGen_origin_prompt/live_5s_final_mix_HOIGen_no_camera_prompt_extended.csv
batch_size: 1
gradient_accumulation_steps: 1
ema_weight: 0.99
ema_start_step: 200
total_batch_size: 32
log_iters: 80
max_checkpoints: 100
max_iters: 1000

negative_prompt: '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'
dfake_gen_update_ratio: 5
image_or_video_shape:
- 1
- 241 # unused in streaming training
- 48
- 80
- 44
distribution_loss: dmd_switch
global_sink: false
trainer: score_distillation
gradient_checkpointing: true
num_frame_per_block: 4
load_raw_video: true
model_kwargs:
  model_name: Wan2.2-TI2V-5B
  timestep_shift: 5.0
  local_attn_size: 12
  sink_size: 1

# Visualization
vis_interval: 40
vis_ema: false
vis_video_lengths:
- 241
val_batch_size: 1
val_data_path: /m2v_intern/raozejing/StreamingCode/dataset/live_5s_final_mix_HOIGen_origin_prompt/live_5s_final_mix_HOIGen_no_camera_prompt_testset_2_prompts_list.csv
val_switch_frame_indices: 81

slice_last_frames: 21

switch_mode: random_choice
switch_choices:
- 41
- 61
- 81
- 101
- 121
- 141
- 161
- 201
- 221

streaming_training: true
streaming_chunk_size: 21
streaming_max_length: 241

streaming_min_new_frame: 16
train_first_chunk: true

last_step_only: false

debug_save_latents: false

## LoRA Configuration
adapter:
  type: "lora"
  rank: 256                    # LoRA rank (typical values: 8, 16, 32, 64)
  alpha: 256                   # LoRA alpha (typically same as rank, but can be different)
  dropout: 0.0                # LoRA dropout rate
  dtype: "bfloat16"          # Data type for LoRA parameters: "bfloat16", "float16", "float32"
  apply_to_critic: true       # Whether to apply LoRA to critic/fake_score model
  verbose: true              # Whether to print all target module names
